all:
  children:
    bastion:
      hosts:
        bastion-host:
          ansible_host: <bastion_public_ip>
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    webservers:
      hosts:
        app-server:
          ansible_host: <app_private_ip>
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@<bastion_public_ip>"'